import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Provider from './components/Provider'
import Navbar from './components/Navbar'
import MainNavbar from './webcomponents/MainNavbar'
// import Products from './webcomponents/Products'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecom App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
   
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        {/* <MainNavbar/> */}
      <Navbar />
      {/* <Products products={[]} error={null}/> */}
        <Provider>
        {children}
        </Provider>
        </body>
    </html>
    
  )
}
